version: '3.8'

services:
  ui:
    container_name: frontend
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your_secret_key_here
      - NEXT_PUBLIC_API_URL=http://backend:8080
      - NODE_OPTIONS='--inspect'
    command: ["pm2-runtime", "npm", "--", "start"]
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - "8080:8080"
    env_file:
      - ./backend/env/production.env
    volumes:
      - ./backend/prisma:/app/backend/prisma
    command: sh -c "npm run migrate:deploy:prod && npm run start:prod"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: media_scrapper
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  db_data: